[package]
name = "alices_ring_cairo_verifier"
version = "0.1.0"
edition = "2024_07"

[dependencies]
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git", branch="msm_copy" }

[dev-dependencies]
cairo_test = "2.8.2" 
