[package]
name = "alices_ring_cairo_verifier"
version = "0.1.0"
edition = "2023_11"

[dependencies]
alexandria_encoding = { git = "https://github.com/keep-starknet-strange/alexandria" }
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git" }

[dev-dependencies]
cairo_test = "2.7.1" 
