[package]
name = "alices_ring_cairo_verifier"
version = "0.1.0"
edition = "2024_07"

[dependencies]
garaga = { git = "https://github.com/keep-starknet-strange/garaga", rev = "fa27403e6aa2c968a369c6da6ddfbd8da36a42f3" }

[dev-dependencies]
cairo_test = "2.8.2" 
